version: '1'
services:
  web:
    type: web
    name: my-react-app
    env: static
    staticPublishPath: dist
    buildCommand: npm run build
    routes:
      - type: rewrite
        source: '/*'
        destination: '/index.html'
